/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author usuario
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mAFD = new javax.swing.JMenu();
        mi_AFD = new javax.swing.JMenuItem();
        mAFND = new javax.swing.JMenu();
        mi_AFND = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mAFD.setText("Automata AFD");

        mi_AFD.setText("Ejecutar Automata AFD");
        mAFD.add(mi_AFD);

        jMenuBar1.add(mAFD);

        mAFND.setText("Automata AFND");

        mi_AFND.setText("Ejecutar Automata AFND");
        mAFND.add(mi_AFND);

        jMenuBar1.add(mAFND);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenu mAFD;
    public javax.swing.JMenu mAFND;
    public javax.swing.JMenuItem mi_AFD;
    public javax.swing.JMenuItem mi_AFND;
    // End of variables declaration//GEN-END:variables
}
